### ISSUE TITLE
Go task synergy 

### ISSUE THREAD

**Issue by gedw99** [pokanop/nostromo#60]
This is really cool.

There is sone synergy for this to be used with go task. 
https://github.com/go-task/task

Go task can reference the aliases!

btw have you tried this on windows ?.
It probably works on Linus , since it works on Mac

**Comment by saheljalal** [comment]
Go task looks really interesting, a powerful Makefile replacement seemingly. It appears much more powerful for automating pipelines. `nostromo` helps build multi-tiered tooling and can likely add aliases to `task` since it's just executing a shell command. Both seem to have many similarities including the config. Will definitely check out go task to learn more about improvements that can be made here.

Unfortunately, I haven't had the bandwidth or time to test on Windows, but have tried to do so on Mac and Linux. As always with open source, I'd love for community contributions or help to improve functionality/reliability and provide a wider breadth of use. Thanks for sharing 👍

**Comment by saheljalal** [comment]
Thanks again for the introduction to `task`, I've created a few issues (#64 , #65 , #66) to track enhancements that could be made to `nostromo` based on features there. Though there are a lot of similarities in the tools, I feel the goals are still vastly different. From what I can tell `nostromo` is for managing global aliases and building multi-tier tools or command trees and `task` is a much more powerful Makefile system for projects. I can learn a lot from task and how they've done things for sure📚

**Comment by gedw99** [comment]
nice one..

i am trying out nostromo.
